### ISSUE TITLE
Code does not build on 1.48.0

### ISSUE THREAD

**Issue by praetp** [jhelwig/unicorn-hat-hd-rs#9]
I am getting:
```
error[E0658]: use of unstable library feature 'array_methods'
   --> src/lib.rs:165:64
    |
165 |             Rotate::RotNone => arr.extend_from_slice(self.leds.as_slice()),
    |                                                                ^^^^^^^^
    |
    = note: see issue #76118 <https://github.com/rust-lang/rust/issues/76118> for more information

error[E0308]: mismatched types
   --> src/lib.rs:165:54
    |
165 |             Rotate::RotNone => arr.extend_from_slice(self.leds.as_slice()),
    |                                                      ^^^^^^^^^^^^^^^^^^^^ expected `u8`, found struct `RGB`
    |
    = note: expected reference `&[u8]`
               found reference `&[RGB<u8>]`

error: aborting due to 2 previous errors; 2 warnings emitted
```

**Comment by BartMassey** [comment]
See Pull Request #10 for a fix.
